package leetcode.easy;

/**
 * 389. Find the Difference
 * <p>
 * Given two strings s and t which consist of only lowercase letters.
 * <p>
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * <p>
 * Find the letter that was added in t.
 */
public class FindTheDifference {
    public char findTheDifference(String s, String t) {
        char diff = 0;

        for (int i = 0; i < s.length(); i++) {
            diff += t.charAt(i) - s.charAt(i);
        }

        diff += t.charAt(t.length() - 1);
        return diff;
    }

    public char findTheDifferenceBit(String s, String t) {
        char diff = 0;
        for (int i = 0; i < s.length(); i++) {
            diff ^= s.charAt(i);
        }
        for (int i = 0; i < t.length(); i++) {
            diff ^= t.charAt(i);
        }
        return diff;
    }
}
